# Generated by Django 4.0.6 on 2022-07-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='image_for_post', verbose_name='Добавь картинку'),
            preserve_default=False,
        ),
    ]
