# Generated by Django 4.0.6 on 2022-07-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='image_for_post/', verbose_name='Добавь картинку'),
        ),
    ]
